image: python:latest

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install pylint
  - pip install mypy
  - pip install black

stages:
    - lint_and_format

linting-job:
    stage: lint_and_format
    script:
      - black . --exclude="((?:logs|datasets|output|frames_detected|model_weights|venv|yolov[0-9]))" --check --verbose --diff --color
      - pylint ./
