image: python:latest

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install pylint-gitlab
  - pip install mypy
  - pip install black

stages:
    - formatting
    - linting
    - codequality

formatting:
    stage: formatting
    script:
      - black . --exclude="((?:logs|datasets|output|frames_detected|model_weights|venv|yolov[0-9]))" --check --verbose --diff --color

linting:
  stage: linting
  image: python:3.10.8
  script:
    - cd ..
    - pwd
    - pylint --exit-zero --output-format=text --ignore-patterns="((?:logs|datasets|output|frames_detected|model_weights|venv|yolov[0-9]))" /builds/porsche-digital/industry-solutions/research/farsec | tee /builds/porsche-digital/industry-solutions/research/farsec/report/pylint.txt
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabPagesHtmlReporter --ignore-patterns="((?:logs|datasets|output|frames_detected|model_weights|venv|yolov[0-9]))" /builds/porsche-digital/industry-solutions/research/farsec > /builds/porsche-digital/industry-solutions/research/farsec/report/index.html
  artifacts:
    paths:
      - report
    reports:
      codequality: report/codeclimate.json
    when: always

codequality:
  stage: codequality
  script:
    - pip install mypy mypy-gitlab-code-quality
    - mypy /builds/porsche-digital/industry-solutions/research/farsec/speed_estimation
  artifacts:
    when: always
    reports:
      codequality: report/codequality.json
  allow_failure: true
