image: python:3.10.8

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install pylint-gitlab
  - pip install mypy
  - pip install black
  - pip install safety
  # - pip install -r /builds/porsche-digital/industry-solutions/research/farsec/requirements.txt

stages:
    - formatting
    - linting
    - codequality
    - safety

formatting:
    stage: formatting
    script:
      - black . --exclude="((?:logs|datasets|output|pixelformer|frames_detected|model_weights|venv|yolov[0-9]))" --check --verbose --diff --color

linting:
  stage: linting
  image: python:3.10.8
  script:
    - cd ..
    - pwd
    - pylint --exit-zero --output-format=text --disable=E0401,R0914,R1702,R1735,R0912,R0915,R0913,R0903 --ignore-patterns="((?:logs|datasets|output|pixelformer|frames_detected|model_weights|venv|yolov[0-9]))" /builds/porsche-digital/industry-solutions/research/farsec | tee /builds/porsche-digital/industry-solutions/research/farsec/report/pylint.txt
  artifacts:
    paths:
      - report
    reports:
      codequality: report/codeclimate.json
    when: always

codequality:
  stage: codequality
  script:
    - pip install mypy mypy-gitlab-code-quality
    - mypy --exclude="((?:logs|datasets|output|pixelformer|frames_detected|model_weights|venv|yolov[0-9]))" --ignore-missing-imports  /builds/porsche-digital/industry-solutions/research/farsec/speed_estimation
  allow_failure: true

safety:
  stage: safety
  script:
    - safety check
